### ISSUE TITLE
Missing script: "dev"

### ISSUE THREAD

**Issue by goutC** [shishkevichd/telegram-chatgpt-bot#1]
npm run dev

npm ERR! Missing script: "dev"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-02-12T01_23_15_114Z-debug-0.log

**Comment by shishkevichd** [comment]
```bash
npm run start
```
